# ==========================================
# DATABASE CONFIGURATION (POSTGRESQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/balance_db
spring.datasource.username=admin_itau
spring.datasource.password=itausecret123@@
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE CONFIGURATION
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# allows to send a group of SQL statements to the database in a single network call.
spring.jpa.properties.hibernate.jdbc.batch_size=50
# It groups several INSERT statements and send them to the database in one go.
spring.jpa.properties.hibernate.order_inserts=true
# It groups several UPDATE statements and send them to the database in one go.
spring.jpa.properties.hibernate.order_updates=true

# ==========================================
# HIKARI CONFIGURATION
# ==========================================
# How many simultaneous connections Java can open with Postgres
spring.datasource.hikari.maximum-pool-size=50
# Minimum number of keep-alive connections in the pool (Avoids the cost of opening new connections).
spring.datasource.hikari.minimum-idle=20
# Maximum time (in ms) a thread can wait for a connection from the pool before throwing an error.
spring.datasource.hikari.connection-timeout=5000
# Maximum time a connection can remain idle before being killed.
spring.datasource.hikari.idle-timeout=30000

# ==========================================
# AWS/SQS CONFIGURATION
# ==========================================
cloud.aws.region.static=sa-east-1
cloud.aws.credentials.access-key=test
cloud.aws.credentials.secret-key=test
cloud.aws.sqs.endpoint=http://localhost:4566
cloud.aws.sqs.queue-name=transacoes-financeiras-processadas
# Allows processing up to 10 messages per batch in parallel per thread
cloud.aws.sqs.listener.max-messages-per-poll=10
cloud.aws.sqs.listener.max-concurrent-messages=150
